# AI WORKPLACE PRODACTIVITY

## Business Problem

The purpose of this project is  to analyze the implementation of AI in the workplace and how it influences  productivity,  workload balance, adoptation and employees' well-being. It is designed for machine learning regression and classification tasks focused on predicting employee productivity and burnout risk.

## Table of Contents

### 1. Data Overview
### 2.Data Loading and Exploration
### 3.Data Cleaning and Preparation
### 4.Business Questions, Key Findings, and Recommendations
### 5.Conclusion

# 1. Data Overview

This dataset used in this analysis was downloaded in Kaggle. Link: https://www.kaggle.com/datasets/vishardmehta/ai-tool-usage-and-workplace-productivity-datasetAnd contains row represents one employee over a monthly period, capturing AI usage, work habits, collaboration, workload, and stress indicators. The dataset models realistic relationships where balanced AI usage can improve productivity, while excessive workload and poor work-life balance increase burnout risk.

## 1.1 Dataset Dictonary

This dataset contains the following key variables :

● **Employee_ID**: Unique identifier assigned to each employee.  
● **job_role**: Employee’s primary job position within the organization.  
● **experience_years**: Total number of years of professional work experience.  
● **ai_tool_usage_hours_per_week**: Number of hours per week the employee spends using AI tools.  
● **tasks_automated_percent**: Percentage of the employee’s tasks that are automated using AI tools.  
● **manual_work_hours_per_week**: Number of hours per week spent on manual (non-automated) tasks.  
● **learning_time_hours_per_week**: Weekly hours spent learning or upskilling on AI tools or related technologies.  
● **deadline_pressure_level**: Level of pressure experienced in meeting deadlines.  
● **meeting_hours_per_week**: Total hours spent in meetings per week.  
● **collaboration_hours_per_week**: Weekly hours spent collaborating with team members.  
● **error_rate_percent**: Percentage of errors in completed tasks.  
● **task_complexity_score**: Score indicating complexity of tasks handled.  
● **focus_hours_per_day**: Average number of focused, uninterrupted working hours per day.  
● **work_life_balance_score**: Self-reported work-life balance score.  
● **burnout_risk_score**: Estimated burnout risk score.

# 2. Data Loadiing and Exploring

## 2.1 Loding the dataset using pandas:

In [6]:
import pandas as pd
#load the datset
df1 = pd.read_csv("ai_productivity_features.csv")
df2 =pd.read_csv("ai_productivity_targets.csv")

## 2.2 Preview the data:

In [19]:
#dispalying  information in our dataset for df1
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Employee_ID                   4500 non-null   object
 1   job_role                      4500 non-null   object
 2   experience_years              4500 non-null   int64
 3   ai_tool_usage_hours_per_week  4500 non-null   float64
 4   tasks_automated_percent       4500 non-null   float64
 5   manual_work_hours_per_week    4500 non-null   float64
 6   learning_time_hours_per_week  4500 non-null   float64
 7   deadline_pressure_level       4500 non-null   object
 8   meeting_hours_per_week        4500 non-null   float64
 9   collaboration_hours_per_week  4500 non-null   float64
 10  error_rate_percent            4500 non-null   float64
 11  task_complexity_score         4500 non-null   int64
 12  focus_hours_per_day           4500 non-null   float64
 13  work_life_balance_score       4500 non-null   float64
 14  burnout_risk_score            4500 non-null   float64
dtypes: float64(10), int64(2), object(3)
memory usage: 527.5+ KB

In [9]:
#dispalying  information in our dataset for df2
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         4500 non-null   object
 1   productivity_score  4500 non-null   float64
 2   burnout_risk_level  4500 non-null   object
dtypes: float64(1), object(2)
memory usage: 105.6+ KB

In [10]:
#prewing the first rows of our dataset df1
df1.head()

,Employee_ID,job_role,experience_years,ai_tool_usage_hours_per_week,tasks_automated_percent,manual_work_hours_per_week,learning_time_hours_per_week,deadline_pressure_level,meeting_hours_per_week,collaboration_hours_per_week,error_rate_percent,task_complexity_score,focus_hours_per_day,work_life_balance_score,burnout_risk_score
0,3c6ca882-3fa3-446b-8208-c92f3f306f06,Writer,19,11.8,28.5,19.2,1.4,High,1.9,2.3,0.20,2,7.1,4.8,10.00
1,02f168cc-7747-4dbd-a868-ea2cfb41e22a,Designer,4,10.8,24.1,23.3,2.6,Low,8.0,9.8,1.82,3,3.4,5.5,6.78
2,d39ce8c9-6e2a-4f86-b888-e2b5f4a18cf7,Developer,6,25.9,69.4,10.0,1.4,Medium,6.8,8.9,5.52,5,4.6,3.8,9.66
3,14511660-d78a-453f-9449-f17cd239ec27,Manager,20,7.9,17.2,25.1,0.2,High,3.5,8.6,1.14,5,5.6,3.9,10.00
4,0597f0bb-ed5a-4e35-94ac-3f0f6a5c2bc2,Developer,15,8.6,20.6,20.1,1.4,Low,5.9,5.3,2.75,10,1.0,7.4,5.38

In [11]:
#prewing the first rows of our dataset df2
df2.head()

                            Employee_ID  productivity_score burnout_risk_level
0  3c6ca882-3fa3-446b-8208-c92f3f306f06                81.0               High
1  02f168cc-7747-4dbd-a868-ea2cfb41e22a                59.2             Medium
2  d39ce8c9-6e2a-4f86-b888-e2b5f4a18cf7                62.4               High
3  14511660-d78a-453f-9449-f17cd239ec27                76.8               High
4  0597f0bb-ed5a-4e35-94ac-3f0f6a5c2bc2                53.7             Medium

In [13]:
#describing the dataset to get the summary statistics for df1
df1.describe()

,experience_years,ai_tool_usage_hours_per_week,tasks_automated_percent,manual_work_hours_per_week,learning_time_hours_per_week,meeting_hours_per_week,collaboration_hours_per_week,error_rate_percent,task_complexity_score,focus_hours_per_day,work_life_balance_score,burnout_risk_score
count,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000
mean,10.427556,10.349667,25.908467,22.372867,2.001756,6.571089,8.249311,2.097044,5.507556,4.694489,4.724689,8.354816
std,5.745073,5.808240,15.157930,6.465516,1.408176,4.683117,3.040733,1.519145,2.861737,1.337197,1.993201,1.813773
min,1.000000,0.000000,0.000000,10.000000,0.000000,1.000000,2.000000,0.100000,1.000000,1.000000,1.000000,3.220000
25%,6.000000,6.000000,14.500000,17.900000,1.000000,3.400000,6.200000,0.710000,3.000000,3.900000,3.300000,6.850000
50%,10.000000,9.700000,24.500000,22.500000,1.700000,5.700000,8.000000,2.000000,6.000000,4.800000,4.700000,9.035000
75%,15.000000,14.300000,36.000000,26.800000,2.700000,8.200000,10.000000,3.290000,8.000000,5.600000,6.200000,10.000000
max,20.000000,30.400000,79.900000,43.300000,11.500000,30.200000,20.000000,6.670000,10.000000,8.000000,10.000000,10.000000

In [14]:
#describing the dataset to get the summary statistics for df2
df2.describe()

       productivity_score
count         4500.000000
mean            64.946600
std             14.297129
min             20.500000
25%             54.975000
50%             64.800000
75%             74.900000
max            100.000000

In [17]:
#checking missing values in each column for df1
df1.isnull().sum()

Employee_ID                     0
job_role                        0
experience_years                0
ai_tool_usage_hours_per_week    0
tasks_automated_percent         0
manual_work_hours_per_week      0
learning_time_hours_per_week    0
deadline_pressure_level         0
meeting_hours_per_week          0
collaboration_hours_per_week    0
error_rate_percent              0
task_complexity_score           0
focus_hours_per_day             0
work_life_balance_score         0
burnout_risk_score              0
dtype: int64

In [18]:
#checking missing values in each column for df2
df2.isnull().sum()

Employee_ID           0
productivity_score    0
burnout_risk_level    0
dtype: int64